[package]
name = "wrpc-interface-http"
version = "0.1.0"
edition = "2021"
description = "wRPC HTTP interface"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvolosatovs/wrpc"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
tracing = { workspace = true, features = ["attributes"] }
wrpc-transport = { workspace = true }
