[package]
name = "wrpc"
version = "0.1.0"
edition = "2021"
description = "WebAssembly RPC framework"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvolosatovs/wrpc"

[features]
default = ["nats", "wasmtime"]

nats = ["dep:wrpc-transport-nats"]
wasmtime = ["dep:wrpc-runtime-wasmtime"]

[workspace]
members = ["crates/*"]

[dependencies]
wrpc-interface-http = { workspace = true }
wrpc-runtime-wasmtime = { workspace = true, optional = true }
wrpc-transport = { workspace = true }
wrpc-transport-nats = { workspace = true, optional = true }
wrpc-types = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
futures = { workspace = true, features = ["async-await"] }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "ansi",
    "env-filter",
    "fmt",
] }

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
async-nats = { version = "0.33", default-features = false }
async-trait = { version = "0.1", default-features = false }
bytes = { version = "1", default-features = false }
futures = { version = "0.3", default-features = false }
leb128 = { version = "0.2", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
tokio = { version = "1", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
wasmtime = { version = "18", default-features = false }
wasmtime-wasi = { version = "18", default-features = false }
wit-parser = { version = "0.13", default-features = false }
wrpc-interface-http = { version = "0.6", path = "./crates/interface-http", default-features = false }
wrpc-runtime-wasmtime = { version = "0.1", path = "./crates/runtime-wasmtime", default-features = false }
wrpc-transport = { version = "0.10", path = "./crates/transport", default-features = false }
wrpc-transport-nats = { version = "0.7", path = "./crates/transport-nats", default-features = false }
wrpc-types = { version = "0.3", path = "./crates/types", default-features = false }
