[package]
name = "wrpc"
version = "0.1.0"
edition = "2021"
description = "WebAssembly RPC framework"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvolosatovs/wrpc"

[features]
bin = [
    "clap",
    "indexmap",
    "reqwest",
    "tokio/io-std",
    "tokio/macros",
    "tokio/rt-multi-thread",
    "tracing",
    "tracing-subscriber",
    "url",
    "wasmcloud-component-adapters",
    "wasmparser",
    "wasmtime",
    "wasmtime-environ",
    "wasmtime-wasi",
    "wasmtime-wasi-http",
    "wit-component",
]
default = ["bin"]

[workspace]
members = ["examples/rust/*"]

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-nats = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"], optional = true }
futures = { workspace = true }
h2 = { workspace = true }
http = { workspace = true }
indexmap = { workspace = true, optional = true }
nats-connect = { workspace = true }
reqwest = { workspace = true, features = ["rustls"], optional = true }
tokio = { workspace = true, features = ["sync"] }
tower-service = { workspace = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter", "fmt"], optional = true }
url = { workspace = true, optional = true }
wasmcloud-component-adapters = { workspace = true, optional = true }
wasmparser = { workspace = true, optional = true }
wasmtime = { workspace = true, features = ["cranelift"], optional = true }
wasmtime-environ = { workspace = true, optional = true } # TODO: Remove
wasmtime-wasi = { workspace = true, optional = true }
wasmtime-wasi-http = { workspace = true, optional = true }
wit-component = { workspace = true, optional = true }
wit-parser = { workspace = true }

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
async-nats = { version = "0.33", default-features = false }
async-recursion = { version = "1", default-features = false }
async-trait = { version = "0.1", default-features = false }
bytes = { version = "1", default-features = false }
clap = { version = "4", default-features = false }
futures = { version = "0.3", default-features = false }
h2 = { version = "0.4", default-features = false }
http = { version = "1", default-features = false }
indexmap = { version = "2", default-features = false }
nats-connect = { version = "0.1", default-features = false }
reqwest = { version = "0.11", default-features = false }
tokio = { version = "1", default-features = false }
tower-service = { version = "0.3", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
url = { version = "2", default-features = false }
wasmcloud-component-adapters = { version = "0.5", default-features = false }
wasmparser = { version = "0.118", default-features = false }
#wasmtime = { path = "../../bytecodealliance/wasmtime/crates/wasmtime", default-features = false }
#wasmtime-environ = { path = "../../bytecodealliance/wasmtime/crates/wasi", default-features = false }
#wasmtime-wasi = { path = "../../bytecodealliance/wasmtime/crates/wasi", default-features = false }
#wasmtime-wasi-http = { path = "../../bytecodealliance/wasmtime/crates/wasi-http", default-features = false }
wasmtime = { git = "https://github.com/rvolosatovs/wasmtime", branch = "wip", default-features = false }
wasmtime-environ = { git = "https://github.com/rvolosatovs/wasmtime", branch = "wip", default-features = false }
wasmtime-wasi = { git = "https://github.com/rvolosatovs/wasmtime", branch = "wip", default-features = false }
wasmtime-wasi-http = { git = "https://github.com/rvolosatovs/wasmtime", branch = "wip", default-features = false }
wit-bindgen = { version = "0.16", default-features = false }
wit-component = { version = "0.19", default-features = false }
wit-parser = { version = "0.13", default-features = false }
