[package]
name = "wrpc-transport-nats"
version = "0.5.0"
edition = "2021"
description = "wRPC NATS transport"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvolosatovs/wrpc"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
async-nats = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
wrpc-transport = { workspace = true }
